project:
  type: website
  output-dir: docs

website:
  title: "Shravan Kumar Kilaparthi"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Resume"
        href: resume.qmd
      - text: "Projects"
        href: projects.qmd
      - text: "Skills"
        href: skills.qmd
      - text: "Leadership"
        href: leadership.qmd
      - text: "Contact"
        href: contact.qmd
    right:
      - text: "Appendix"
        href: appendix.qmd
      - icon: linkedin
        href: "https://www.linkedin.com/in/shravan-kumar-9b1096141/"
      - icon: envelope
        href: "mailto:kilaparthishravan@gmail.com"

format:
  html:
    theme: flatly
    toc: false
    smooth-scroll: true
    css: styles.css